<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'BookModel' => $baseDir . '/Model/Admin/listBook.php',
    'ChuDeModel' => $baseDir . '/Model/Admin/chude.php',
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'DanhMucModel' => $baseDir . '/Model/Admin/danhmuc.php',
    'HinhAnhModel' => $baseDir . '/Model/Admin/imageBook.php',
    'HinhThucModel' => $baseDir . '/Model/Admin/hinhthuc.php',
    'NgonNguModel' => $baseDir . '/Model/Admin/ngonngu.php',
    'NhaXuatBanModel' => $baseDir . '/Model/Admin/nhaxuatban.php',
    'TacGiaModel' => $baseDir . '/Model/Admin/tacGia.php',
    'TheLoaiModel' => $baseDir . '/Model/Admin/theloai.php',
);
