<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitd751713988987e9331980363e24189ce
{
    public static $classMap = array (
        'BookModel' => __DIR__ . '/../..' . '/Model/Admin/listBook.php',
        'ChuDeModel' => __DIR__ . '/../..' . '/Model/Admin/chude.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'DanhMucModel' => __DIR__ . '/../..' . '/Model/Admin/danhmuc.php',
        'HinhAnhModel' => __DIR__ . '/../..' . '/Model/Admin/imageBook.php',
        'HinhThucModel' => __DIR__ . '/../..' . '/Model/Admin/hinhthuc.php',
        'NgonNguModel' => __DIR__ . '/../..' . '/Model/Admin/ngonngu.php',
        'NhaXuatBanModel' => __DIR__ . '/../..' . '/Model/Admin/nhaxuatban.php',
        'TacGiaModel' => __DIR__ . '/../..' . '/Model/Admin/tacGia.php',
        'TheLoaiModel' => __DIR__ . '/../..' . '/Model/Admin/theloai.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->classMap = ComposerStaticInitd751713988987e9331980363e24189ce::$classMap;

        }, null, ClassLoader::class);
    }
}
